version: "3"
services:
  mongoDB:
    restart: always
    container_name: 'masivian-mongo'
    image: mongo
    ports: 
      - 27017-27019:27017-27019
    environment:
      MONGO_INITDB_DATABASE: masivian-roulette
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - masivian
      
  masivian-roulette:
    restart: always
    container_name: 'masivian-roulette'
    build:
      context: .
    ports: 
      - 8080:8080
    environment:
      MONGO_SERVER: mongoDB
      MONGO_DATABASE: masivian-roulette
      MONGO_USERNAME: root
      MONGO_PASSWORD: rootpassword
    depends_on:
      - mongoDB
    networks:
      - masivian
      
networks:
  masivian:
volumes:
  mongodb_data_container: